# This is a basic workflow to help you get started with Actions

name: CIdemoJavaStart

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest          # downloads a copy of your repository on the runner

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8        #configures the Java 1.8 JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Change wrapper permissions
        run: chmod +x ./gradlew     #to gain gradlew run permission
      - name: Build with Gradle
        run: ./gradlew build  
        #runs the gradlew wrapper script to ensure that your code builds, tests pass, and a package can be created	
